# Generated by Django 5.0.1 on 2024-02-19 14:57

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Project Description')),
                ('description', models.CharField(max_length=1000, verbose_name='Project Description')),
                ('reward', models.PositiveSmallIntegerField(verbose_name='Project Reward')),
                ('difficulty', models.CharField(choices=[('0', 'beginner'), ('1', 'intermediate'), ('2', 'advanced'), ('3', 'pro')], max_length=1, verbose_name='Project Difficulty')),
                ('project_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
                ('enrolled_profiles', models.ManyToManyField(blank=True, related_name='enrolled_profiles', to='accounts.profile')),
            ],
            options={
                'ordering': ('-date_created', '-date_updated'),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_link', models.URLField(max_length=500, verbose_name='Solution Repository')),
                ('live_link', models.URLField(max_length=500, verbose_name='Live Solution')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='accounts.profile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
