# Generated by Django 5.0.1 on 2024-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Project Name'),
        ),
    ]
