# Generated by Django 5.0.1 on 2024-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_solution_date_updated_solution_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='live_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Live Solution'),
        ),
    ]
