# Generated by Django 5.0.1 on 2024-02-26 15:16

import django.contrib.postgres.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_solution_live_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reward',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, verbose_name='Project Tags'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Solution Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('0', 'beginner'), ('1', 'intermediate'), ('2', 'advanced')], max_length=1, verbose_name='Project Difficulty'),
        ),
    ]
